# Generated by Django 4.2.6 on 2024-02-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='depts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=30)),
            ],
        ),
    ]
