# Generated by Django 5.0.2 on 2024-03-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internships',
            name='domain',
            field=models.CharField(default='Web Development', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internships',
            name='projectName',
            field=models.CharField(default='Internship Dashboard', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internships',
            name='status',
            field=models.CharField(default='Ongoing', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(default='B', max_length=6),
            preserve_default=False,
        ),
    ]
