# Generated by Django 4.1.13 on 2024-03-04 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Internships', '0002_internships_domain_internships_projectname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='depts',
        ),
    ]
