# Generated by Django 4.2.6 on 2024-02-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internships', '0002_depts'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('rollno', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('dept', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='imagesstudent/')),
            ],
        ),
    ]
