# Generated by Django 4.1.13 on 2024-03-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internships', '0003_delete_depts'),
    ]

    operations = [
        migrations.CreateModel(
            name='depts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=30)),
                ('no_of_students', models.IntegerField()),
                ('no_of_interns', models.IntegerField()),
                ('no_of_unique_internships', models.IntegerField()),
            ],
        ),
    ]
