# Generated by Django 4.2.6 on 2024-02-13 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Internships', '0004_internships'),
    ]

    operations = [
        migrations.AddField(
            model_name='internships',
            name='certificate',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='certificates/'),
            preserve_default=False,
        ),
    ]
