# Generated by Django 4.1.13 on 2024-02-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internships', '0005_internships_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internships',
            old_name='type',
            new_name='intern_type',
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
